[2025-05-30T13:06:27.362+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_ecobici.procesar_datos manual__2025-05-30T13:05:49.085970+00:00 [queued]>
[2025-05-30T13:06:27.376+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_ecobici.procesar_datos manual__2025-05-30T13:05:49.085970+00:00 [queued]>
[2025-05-30T13:06:27.376+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-30T13:06:27.439+0000] {taskinstance.py:2191} INFO - Executing <Task(SparkSubmitOperator): procesar_datos> on 2025-05-30 13:05:49.085970+00:00
[2025-05-30T13:06:27.443+0000] {standard_task_runner.py:60} INFO - Started process 174 to run task
[2025-05-30T13:06:27.446+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_ecobici', 'procesar_datos', 'manual__2025-05-30T13:05:49.085970+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_ecobici.py', '--cfg-path', '/tmp/tmpnyjd4ud2']
[2025-05-30T13:06:27.449+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask procesar_datos
[2025-05-30T13:06:27.574+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_ecobici.procesar_datos manual__2025-05-30T13:05:49.085970+00:00 [running]> on host 21812af8c39c
[2025-05-30T13:06:27.724+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_ecobici' AIRFLOW_CTX_TASK_ID='procesar_datos' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T13:05:49.085970+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-30T13:05:49.085970+00:00'
[2025-05-30T13:06:27.753+0000] {base.py:83} INFO - Using connection ID 'spark_default' for task execution.
[2025-05-30T13:06:27.755+0000] {spark_submit.py:341} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /app/dags/scripts/procesar_ecobici.py
[2025-05-30T13:06:27.806+0000] {spark_submit.py:492} INFO - JAVA_HOME is not set
[2025-05-30T13:06:27.826+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 423, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /app/dags/scripts/procesar_ecobici.py. Error code is: 1.
[2025-05-30T13:06:27.833+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_ecobici, task_id=procesar_datos, execution_date=20250530T130549, start_date=20250530T130627, end_date=20250530T130627
[2025-05-30T13:06:27.898+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 19 for task procesar_datos (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose --queue root.default /app/dags/scripts/procesar_ecobici.py. Error code is: 1.; 174)
[2025-05-30T13:06:27.942+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-30T13:06:27.984+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
